### PR TITLE
Fix bug in `dealias!` functionality

### LINKED ISSUE #281: Dealiasing in >1 dimensions
Seems like in >1 dimensions the `dealias!` zeros out wavenumbers, e.g.
```julia
|kx * Lx/2π| >nx/3 AND |ky * Ly/2π|>ny/3
```
instead of 
```julia
|kx * Lx/2π| >nx/3 OR |ky * Ly/2π|>ny/3
```

### PR DESCRIPTION
**Pull request by navidcy**
For >1 dimensions, dealiasing should be done independently in each dimension. E.g.
```julia
|kx * Lx/2π| >nx/3 OR |ky * Ly/2π|>ny/3
```
instead of the current implementation of
```julia
|kx * Lx/2π| >nx/3 AND |ky * Ly/2π|>ny/3
```

Closes #281.

### CODE REVIEW

File: src/domains.jl [hunk 1]
```diff
@@ -316,44 +316,47 @@ function getaliasedwavenumbers(nk, nkr, aliasfraction)
...
+  dealias!(a, grid, kalias)
   
   return nothing
 end
 
-function dealias!(a, g::TwoDGrid, kalias)
-  @views @. a[kalias, g.lalias, :] = 0
+function dealias!(a, grid::TwoDGrid, kalias)
+  @views @. a[kalias, :, :] = 0
+  @views @. a[:, grid.lalias, :] = 0
```
Comment (glwagner) [inline src/domains.jl:344]: Good!

**Review by glwagner — APPROVED** [review]
Seems legit
